name: teems-haskell
version: 0.1.0.0
github: "cideM/teems-haskell"
license: BSD3
author: "Florian Beeres"
maintainer: "yuuki@protonmail.com"
copyright: "GNU"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/cideM/teems-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - trifecta
  - directory
  - aeson
  - containers
  - parsers
  - text
  - safe-exceptions
  - vector
  - scientific
  - bytestring

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -Wall

executables:
  teemsh:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - teems-haskell
      - optparse-applicative
      - Glob

tests:
  teems-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - teems-haskell
      - hspec
